### ISSUE TITLE
建议做成gitbook

### ISSUE THREAD

**Issue by QianXuX** [huzidaha/react-naive-book#1]

**Comment by huzidaha** [comment]
感谢你的建议！但 gitbook 也许暂时不考虑。因为本教程后续可能提供视频版本，需要更好的定制性。

**Comment by wizardforcel** [comment]
其实在根目录下创建`SUMMARY.md`，列出目录就可以了，不需要太多东西。

**Comment by aaawhz** [comment]
看样子你是想做成视频 到慕课网上卖钱， 顺便解读下源码 和 带上项目实践， 说不定可以赚个几十万呢。

**Comment by aaawhz** [comment]
maybe you can in several 0 0 0 0 yuan/
