### ISSUE TITLE
问个题外话！

### ISSUE THREAD

**Issue by Bruce-sz** [huzidaha/react-naive-book#3]
邮箱：huzidaha@126.com
知乎：@胡子大哈
专栏：@前端大哈
加入《React.js 小书》读者交流群，一起讨论、交流、学习前端技术。

_**上面提到交流群号是多少？**_谢谢~~

**Comment by huzidaha** [comment]
微信扫一扫下面的图片就可以了，或者手动输入我微信：huzidaha-me。
