### ISSUE TITLE
不知访问不了

### ISSUE THREAD

**Issue by qiutian00** [huzidaha/react-naive-book#36]
### 访问效果
![image](https://user-images.githubusercontent.com/24382500/59476933-8aae8b00-8e85-11e9-8f8d-d81fa3d975ca.png)
### error info
![image](https://user-images.githubusercontent.com/24382500/59477088-3a83f880-8e86-11e9-8bae-e09e1d4e786f.png)

**Comment by pubdreamcc** [comment]
线上地址：http://huziketang.mangojuice.top/books/react/

**Comment by qiutian00** [comment]
@pubdreamcc 多谢
