### ISSUE TITLE
《挂载阶段的组件生命周期（二）》代码错误

### ISSUE THREAD

**Issue by zxhycxq** [huzidaha/react-naive-book#4]
您好，感谢您的教程
在章节  [挂载阶段的组件生命周期（二）](http://huziketang.com/books/react/lesson19)中，

```javascript

class Index extends Component {
  constructor () {
    super()
    this.state = { isShowClock: true }
  }

  handleShowOrHide () {
    this.setState({
      isShowClock: !this.state.isShowClock
    })
  }
```

第一行`Component`前面应该加上 “Reacr.”
博主的像是React Native 的写法。

另外有两个问题想请教下博主：
1、这种.md文档是如何做出在线书籍的？（以您这本书为例，阮一峰老师的ES6教程似乎也是如此）
2、文中的做图软件是什么？
谢谢了。

**Comment by JohannLai** [comment]
看了一下close的issue。
我回答一下后面两个问题：
1.jekyll ，hexo 也可以，其实就是[github pages](https://pages.github.com/)
2.博主说的 --- > keynote

今天群里也有讨论你的第一个问题，其实是 你也有看到 
```javascript
 import { Component  } from 'react'
```
后面就不用继续写 `react.Component`了

另外，ES5的语法糖是`createClass`

**Comment by zxhycxq** [comment]
@JohannLai 
哦，原来如此，没注意，谢谢了。 
制作在线书籍这个，我知道是那几种，就是不知道如何用markdown编译成了html，并且可以是有目录的。
