### ISSUE TITLE
请教个问题，在redux的智能组件中为了控制页面展示，操作该组件的react的原始state是否合适

### ISSUE THREAD

**Issue by 1gehunzi** [huzidaha/react-naive-book#7]
看了您的文章受益匪浅。想请教一下：在项目中使用了redux,知道智能组件和展示组件的区别。可不可以在智能组件中使用react原始的this.state来控制自身内容展示和隐藏。即操作this.setState()的方法。

**Comment by huzidaha** [comment]
@xiyuanyuan 当然是可以的，其实个人蛮建议将非共享的状态都放到 Smart Component 的 state 当中，而不是放到 redux 的 store 里面。

**Comment by 1gehunzi** [comment]
谢谢。  了解了。
